project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"

  navbar:  
    left:
      - href: index.qmd
        text: About
        icon: person-fill
        
      - href: Analysis.qmd
        text: Modern Data Analysis Project
        icon: bar-chart-line-fill
    

format:
  html:
    backgroundcolor: "#f0f8ff"
    fontcolor: "#0047AB"
    theme: 
      - lumen
      - custom.scss


